name: mistralai/Mistral-7B-Instruct-v0.3
tokenizer_name: ${.name}
tokenizer_padding_side: left
context_size: 32_000
compile: true
torch_dtype: bfloat16
attn_implementation: eager
quantization: null
untrained: false
