content: |
  Given the following statement, determine whether it is True or False based on common knowledge. Answer only with the `True` or `False`.

  Statement: {statement}
  Answer:

statement_key: statement
label_mode: binary
use_prompt: true
