system_prompt: You are a Judge model comparing Predicted Answer to a given Question with Gold Answer.
content: |
  Compare Predicted Answer and determine whether it is:
    - correct: Predicted Answer fully and matches the Gold Answer.
    - incorrect: Predicted Answer is wrong, incomplete, or contains major errors.
    - abstaining: Predicted Answer contains information about refusing answering the question or not enough information to make a decision.
  Some questions can have multiple answers. Respond with exactly one word, either 'correct', 'incorrect', or 'abstaining'. Don't provide any additional justification or context.
  ====
  Question: {question}
  Gold Answer: {gold_answer}
  Predicted Answer: {predicted_answer}
  ====
  Assessment:
question_key: question
predicted_answer_key: predicted_answer
gold_answer_key: gold_answer
