system_prompt: You are a Judge model evaluating the answer to a given question.
content: |
  Based on your evaluation, respond with one word: correct, incorrect, or abstaining.
  Some question can have multiple answers, in which case you should respond correct if there is a matching answer.

  Correct: The answer fully and accurately addresses the question.
  Incorrect: The answer is wrong, incomplete, or contains major errors.
  Abstaining: There is not enough information to judge, or the question is unclear.

  Question: {question}
  Predicted answer: {predicted_answer}
  Gold answer: {gold_answer}

  ====
  Assessment:
question_key: question
predicted_answer_key: predicted_answer
gold_answer_key: gold_answer
