defaults:
  - llm: ???
  - dataset: ???
  - prompt: ???
  - _self_

batch_size: 64
generate_kwargs:
  max_new_tokens: ${dataset.max_answer_tokens}
  do_sample: true
  temperature: 1.0
  return_dict_in_generate: true # allows to retrieve activations etc.
results_dir: ???
random_seed: ???
