name: custom/common_claim
cls_path: hallucinations.config.CsvDatasetConfig
dataset_url: https://raw.githubusercontent.com/Algorithmic-Alignment-Lab/CommonClaim/main/common_claim.csv
local_dataset_path: data/datasets/common_claim/dataset.csv
test_split_name: ""
max_answer_tokens: 1
target_column_name: label
question_column_name: question

# label_mode: binary
# !!!: Instead choosing here load the label_mode from the prompt config
# Available options: binary, multi, binary_with_neither
# binary: for two classes, i.e., "true_vs_false".
# multi: for three classes, i.e., "true_vs_false_vs_neither".
# binary_with_neither: for the case where the "neither" class is combined, i.e., "true_and_false_vs_neither"
