name: TimoImhof/TriviaQA-in-SQuAD-format
cls_path: hallucinations.config.TriviaQaDatasetConfig
test_split_name: unmodified
max_answer_tokens: 50 # llama-3.1 tokenizer (without special tokens): {'max': 24, 'mean': 4.63083385334687, 'median': 4, 'min': 2}
target_column_name: answers
question_column_name: question
test_split_ratio: 0.25
